import type { Metadata } from "next";
<<<<<<< HEAD
import {
    Montserrat,
    Hanken_Grotesk,
    Space_Grotesk,
    JetBrains_Mono,
} from "next/font/google";
import localFont from "next/font/local";
=======
import { Geist, Geist_Mono } from "next/font/google";
>>>>>>> origin/main
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

<<<<<<< HEAD
const hanken_grotesk = Hanken_Grotesk({
    variable: "--font-hanken-grotesk",
    subsets: ["latin"],
    weight: ["300", "400", "600", "700", "800", "900"],
});

const space_grotesk = Space_Grotesk({
    variable: "--font-space-grotesk",
    subsets: ["latin"],
    weight: ["300", "400", "600", "700"],
});

const jetBrainsMono = JetBrains_Mono({
    variable: "--font-jetbrains-mono",
    subsets: ["latin"],
    weight: ["300", "400", "600", "700", "800"],
=======
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
>>>>>>> origin/main
});

const ethnocentric = localFont({
    src: "../public/fonts/Ethnocentric-Regular.otf",
    variable: "--font-ethnocentric",
    weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
<<<<<<< HEAD
    return (
        <html
            lang="en"
            className={`${montserrat.variable} ${hanken_grotesk.variable} ${jetBrainsMono.variable} ${ethnocentric.variable} ${space_grotesk.variable} antialiased`}
        >
            <body className="min-h-screen">
                <Navbar />

                {children}

                <Footer />
            </body>
        </html>
    );
=======
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
>>>>>>> origin/main
}
